export const REGISTER_FNAME_CHANGED = 'register_fname_changed'
export const REGISTER_LNAME_CHANGED = 'register_lname_changed'
export const REGISTER_EMAIL_CHANGED = 'register_email_changed'
export const REGISTER_PASSWORD_CHANGED = 'register_password_changed'
export const REGISTER_PHONENUMBER_CHANGED = 'register_phonenumber_changed'
export const REGISTER_LENDER_LOADING = 'register_lender_loading'
export const REGISTER_LENDER_FAILURE = 'register_lender_failure'
export const REGISTER_LENDER_SUCCESS = 'register_lender_success'

export const LOGIN_EMAIL_CHANGED = 'login_email_changed'
export const LOGIN_PASSWORD_CHANGED = 'login_password_changed'
export const LOGIN_LENDER_LOADING = 'login_lender_loading'
export const LOGIN_LENDER_FAIL = 'login_lender_fail'
export const LOGIN_LENDER_SUCCESS = 'login_lender_success'

export const LOGOUT_LENDER = 'logout_lender'