// WARNING: DO NOT EDIT. This file is Auto-Generated by AWS Mobile Hub. It will be overwritten.

// Copyright 2017-2018 Amazon.com, Inc. or its affiliates (Amazon). All Rights Reserved.
// Code generated by AWS Mobile Hub. Amazon gives unlimited permission to
// copy, distribute and modify it.

// AWS Mobile Hub Project Constants
const awsmobile = {
    'aws_app_analytics': 'enable',
    'aws_cognito_identity_pool_id': 'us-east-1:c101c0c6-9b49-4b30-b6f3-316e6d26f6ac',
    'aws_cognito_region': 'us-east-1',
    'aws_content_delivery': 'enable',
    'aws_content_delivery_bucket': 'lenderapptest-hosting-mobilehub-817429442',
    'aws_content_delivery_bucket_region': 'us-east-1',
    'aws_content_delivery_cloudfront': 'enable',
    'aws_content_delivery_cloudfront_domain': 'd2jrlthg7yi80f.cloudfront.net',
    'aws_mobile_analytics_app_id': '2a6e0ee6ede24319bbd5f208c71f5b91',
    'aws_project_id': 'f8055710-7763-4f29-b5fd-d2fe2f730bf6',
    'aws_project_name': 'lender-app-test',
    'aws_project_region': 'us-east-1',
    'aws_resource_name_prefix': 'lenderapptest-mobilehub-817429442',
}

export default awsmobile;
